# Generated by Django 5.2.5 on 2025-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='На какую дату забронирован стол', verbose_name='Дата бронирования')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Когда было создано бронирование', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Уникальный номер стола', verbose_name='Номер стола')),
                ('image', models.ImageField(blank=True, help_text='Изображение стола (необязательно)', null=True, upload_to='photo', verbose_name='Фото стола')),
                ('capacity', models.IntegerField(help_text='Количество мест за столом', verbose_name='Вместимость')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен ли стол для бронирования', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['number'],
            },
        ),
    ]
