# Generated by Django 5.2.5 on 2025-08-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Кто забронировал стол', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(help_text='Какой стол забронирован', on_delete=django.db.models.deletion.CASCADE, to='booking.table', verbose_name='Стол'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('table', 'booking_date')},
        ),
    ]
