# Generated by Django 5.2.5 on 2025-08-18 15:24

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Уникальный токен для подтверждения бронирования', null=True, unique=True, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Время, когда бронирование было подтверждено', null=True, verbose_name='Подтверждено в'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Подтверждено ли бронирование пользователем', verbose_name='Подтверждено'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_confirmed', True)), fields=('table', 'booking_date'), name='unique_confirmed_booking_per_table_date'),
        ),
    ]
