# Generated by Django 5.2.5 on 2025-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00', '10:00-12:00'), ('12:00', '12:00-14:00'), ('14:00', '14:00-16:00'), ('16:00', '16:00-18:00'), ('18:00', '18:00-20:00'), ('20:00', '20:00-22:00')], default='12:00', max_length=5),
        ),
    ]
